import { CATEGORY_META } from '@/lib/categories';

export default function CampaignForm({ action, campaign, banner, submitLabel }: { action: (formData: FormData) => void; campaign?: any; banner?: any; submitLabel: string }) {
  const localDate = (date?: string | null) => date ? new Date(date).toISOString().slice(0, 16) : '';
  return <form action={action} className="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]">
    <section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 sm:p-8">
      <div><p className="text-xs font-black text-teal-700">פרטי הקמפיין</p><h2 className="mt-1 text-xl font-black">תזמון וסטטוס</h2></div>
      <label className="block text-sm font-bold">שם פנימי<input name="name" required defaultValue={campaign?.name ?? ''} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal" placeholder="לדוגמה: השקת מוצר קיץ" /></label>
      <div className="grid gap-5 sm:grid-cols-3"><label className="block text-sm font-bold">סטטוס<select name="status" defaultValue={campaign?.status ?? 'draft'} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"><option value="draft">טיוטה</option><option value="active">פעיל</option><option value="paused">מושהה</option></select></label><label className="block text-sm font-bold">התחלה<input type="datetime-local" name="starts_at" defaultValue={localDate(campaign?.starts_at)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal" /></label><label className="block text-sm font-bold">סיום<input type="datetime-local" name="ends_at" defaultValue={localDate(campaign?.ends_at)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal" /></label></div>
      <div className="border-t border-slate-100 pt-5"><p className="text-xs font-black text-violet-700">הבאנר</p><h2 className="mt-1 text-xl font-black">קריאייטיב ומיקום</h2></div>
      <label className="block text-sm font-bold">כותרת הבאנר<input name="alt_text" required defaultValue={banner?.alt_text ?? ''} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal" /></label>
      <label className="block text-sm font-bold">כתובת תמונה<input name="image_url" required defaultValue={banner?.image_url ?? ''} dir="ltr" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-left font-normal" placeholder="https://... או /images/..." /></label>
      <label className="block text-sm font-bold">קישור יעד<input name="target_url" required defaultValue={banner?.target_url ?? ''} dir="ltr" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-left font-normal" placeholder="https://..." /></label>
      <div className="grid gap-5 sm:grid-cols-3"><label className="block text-sm font-bold">מיקום<select name="placement" defaultValue={banner?.placement ?? 'home_top'} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal"><option value="home_top">ראש דף הבית</option><option value="article_top">ראש כתבה</option><option value="article_bottom">תחתית כתבה</option><option value="footer">פוטר</option></select></label><label className="block text-sm font-bold">קטגוריה<select name="category" defaultValue={banner?.category ?? ''} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal"><option value="">כל האתר</option>{Object.entries(CATEGORY_META).map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}</select></label><label className="block text-sm font-bold">עדיפות<input type="number" min="1" max="100" name="weight" defaultValue={banner?.weight ?? 1} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal" /></label></div>
      <button className="rounded-xl bg-slate-950 px-6 py-3 font-black text-white">{submitLabel}</button>
    </section>
    <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-5 lg:sticky lg:top-24"><h2 className="font-black">תצוגה מקדימה</h2><div className="relative mt-4 aspect-[16/7] overflow-hidden bg-slate-900">{banner?.image_url ? <img src={banner.image_url} alt="" className="h-full w-full object-cover opacity-60" /> : <div className="grid h-full place-items-center text-sm text-white/40">התמונה תופיע כאן לאחר השמירה</div>}<div className="absolute inset-0 bg-gradient-to-l from-slate-950/90 to-transparent" /><span className="absolute inset-x-5 bottom-5 text-lg font-black text-white">{banner?.alt_text || 'כותרת הבאנר'}</span></div><p className="mt-4 text-xs leading-6 text-slate-500">קמפיין פעיל יוצג רק בין תאריך ההתחלה והסיום. ללא תאריכים הוא יוצג מיד ועד לעצירה ידנית.</p></aside>
  </form>;
}
