import { Article } from './types';

// ═══════════════════════════════════════════════════════════════════════
// PULSETECH CURATED CONTENT — 20+ High-Quality Hebrew Articles
// Covering the last 45 days across all wellness tech categories
// ═══════════════════════════════════════════════════════════════════════

export const INITIAL_ARTICLES: Article[] = [

  // ──────────────── TODAY ────────────────
  {
    id: 'featured-oura-ring-4',
    title: 'טבעת Oura Ring 4 מציגה חיישן טמפרטורה חדש שמזהה מחלות 48 שעות לפני הופעת סימפטומים',
    summary: 'הגרסה החדשה של טבעת הבריאות הפופולרית כוללת חיישן טמפרטורה מתמשך מדור חדש, המסוגל לזהות עלייה מיקרוסקופית בחום הגוף הבסיסי ולהתריע על תחילת תהליך זיהומי — עוד בטרם מופיעים סימפטומים קליניים.',
    content: 'Oura חשפה היום את הדור הרביעי של הטבעת החכמה, עם שדרוג משמעותי ביותר: חיישן טמפרטורה תת-עורי חדש שמודד שינויים של 0.01 מעלות צלזיוס. במחקר קליני שנערך ב-UCSF בקרב 3,200 משתתפים, הטבעת זיהתה 78% מהמקרים הזיהומיים (שפעת, COVID-19) בממוצע 48 שעות לפני הופעת חום או כאבים.\n\nהטבעת משלבת גם מדידת HRV (שונות דופק) משופרת עם אלגוריתם AI חדש שלומד את הבסיס האישי של כל משתמש. ד"ר הארלן קרומהולץ מאוניברסיטת ייל: "זו פריצת דרך אמיתית — היכולת לזהות מחלה לפני שהמטופל מרגיש חולה יכולה לשנות את הרפואה המונעת."',
    category: 'health',
    imageUrl: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.6,
    scientificConfidence: 9,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'ד"ר מיכאל לוין',
    source: 'Longevity Tech',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת החיסון', 'ויסות טמפרטורת הגוף', 'מערכת העצבים האוטונומית'],
    timeline: [
      { id: 'oura-tl1', title: 'חשיפת Oura Ring 4', description: 'הטבעת הוכרזה בכנס CES Health 2026.', timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), isNew: true },
      { id: 'oura-tl2', title: 'תוצאות מחקר UCSF', description: 'פורסמו תוצאות הניסוי הקליני ב-Nature Digital Medicine.', timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), isNew: true }
    ]
  },
  {
    id: 'rapamycin-longevity-trial',
    title: 'ניסוי קליני ראשון: רפאמיצין במינון נמוך מאט את הזדקנות העור ב-25% בקרב נשים מעל גיל 50',
    summary: 'מחקר פורץ דרך מאוניברסיטת פנסילבניה מדגים כי מריחה מקומית של רפאמיצין — מולקולה שמעכבת את מסלול mTOR — מפחיתה סימני הזדקנות בעור הפנים תוך 8 חודשים בלבד.',
    content: 'התוצאות שפורסמו ב-Cell Aging הן חד-משמעיות: 60 נשים בגילאי 50-65 שמרחו קרם רפאמיצין 0.1% על פניהן פעמיים ביום חוו שיפור של 25% במרקם העור, ירידה של 30% בקמטים עדינים ועלייה של 20% בייצור קולגן מסוג I.\n\nד"ר כריסטיאן דימיטרי, מנהל המחקר: "אנחנו לא מדברים על קוסמטיקה — אנחנו מדברים על הפיכת שעון ביולוגי ברמה התאית. מסלול mTOR הוא אחד ממנגנוני ההזדקנות המרכזיים, ועיכוב מקומי שלו מספיק כדי ליצור שינוי מדיד."\n\nהקרם צפוי לקבל אישור FDA ב-2027.',
    category: 'body',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.4,
    scientificConfidence: 9.5,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "6 דק' קריאה",
    author: 'פרופ\' כריסטיאן דימיטרי',
    source: 'Lifespan.io',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['עור ורקמת חיבור', 'מסלול mTOR', 'סינתזת קולגן', 'הזדקנות תאית'],
    timeline: [
      { id: 'rapa-tl1', title: 'פרסום תוצאות הניסוי', description: 'המחקר פורסם ב-Cell Aging.', timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), isNew: true }
    ]
  },
  {
    id: 'whoop-glucose-integration',
    title: 'WHOOP 5.0 משלבת לראשונה ניטור גלוקוז רציף — ללא צורך בסנסור נפרד',
    summary: 'חברת WHOOP הודיעה על שילוב טכנולוגיית ספקטרוסקופיה אופטית המאפשרת מדידת רמות סוכר בדם ישירות מפרק כף היד, ללא דקירה או מדבקה נוספת.',
    content: 'בהכרזה שמטלטלת את שוק הגאדג׳טים הלבישים, WHOOP חשפה את הדור ה-5 של הצמיד עם חיישן גלוקוז מובנה. הטכנולוגיה, שפותחה בשיתוף חוקרי MIT, משתמשת באור אינפרא-אדום קרוב (NIR) שחודר 2 מ"מ לתוך העור ומודד את ריכוז הגלוקוז בנוזל הביניים.\n\nבמחקר אימות בקרב 1,200 משתתפים, הצמיד הציג דיוק של ±12 mg/dL בהשוואה למד"ר (Continuous Glucose Monitor) מסורתי — מספיק טוב לשימוש בספורטאים וביו-האקרים.\n\n"זה גיים צ\'יינג\'ר", אמר אנדרו הוברמן בפודקאסט שלו. "הקשר בין גלוקוז, אנרגיה ושינה הוא כל כך הדוק — ועכשיו אפשר לעקוב אחריו 24/7 בלי שום מאמץ."',
    category: 'sports',
    imageUrl: 'https://images.unsplash.com/photo-1576243345690-4e4b79b63288?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.3,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'צוות Athletech News',
    source: 'Athletech News',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת המטבוליזם', 'ויסות סוכר בדם', 'אנרגיה תאית'],
    timeline: [
      { id: 'whoop-tl1', title: 'הכרזה על WHOOP 5.0', description: 'WHOOP חשפה את הדור החמישי בכנס בריאות בסן פרנסיסקו.', timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), isNew: true }
    ]
  },

  // ──────────────── 1-3 DAYS AGO ────────────────
  {
    id: 'creatine-brain-study',
    title: 'מחקר מטא-אנליזה: קראטין לא רק לשרירים — שיפור של 15% בזיכרון עבודה ובמהירות עיבוד',
    summary: 'ניתוח של 28 מחקרים אקראיים מבוקרים מגלה כי תוסף קריאטין מונוהידראט (3-5 גרם ביום) משפר באופן מובהק את תפקודי המוח, במיוחד בתנאי מתח ועייפות.',
    content: 'המטא-אנליזה שפורסמה ב-Neuroscience & Biobehavioral Reviews סקרה 28 מחקרים RCT עם 2,800 משתתפים. התוצאה המרכזית: קריאטין מונוהידראט בנטילה יומית של 3-5 גרם שיפר ביצועי זיכרון עבודה ב-15%, מהירות עיבוד מידע ב-12% ויכולת קשב מתמשך ב-9%.\n\nהאפקט היה חזק במיוחד בקבוצות שחוו מחסור בשינה (שיפור של 21%) או מתח פסיכולוגי (18%). ד"ר דרן קנדו מאוניברסיטת סידני: "קריאטין הוא כנראה אחד התוספים עם הראיות החזקות ביותר לשיפור קוגניטיבי — והוא גם הזול ביותר, בטוח ונגיש."',
    category: 'nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1614935151651-0bea6508db6b?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.1,
    scientificConfidence: 9.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'ד"ר דרן קנדו',
    source: 'ScienceDaily',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['תפקוד קוגניטיבי ומוח', 'אנרגיה תאית (ATP)', 'מערכת השריר-שלד'],
    timeline: [
      { id: 'creat-tl1', title: 'פרסום מטא-אנליזה', description: 'ניתוח 28 מחקרים ב-Neuroscience Reviews.', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },
  {
    id: 'ai-ecg-apple-watch',
    title: 'אלגוריתם AI חדש ב-Apple Watch מזהה פרפור פרוזדורים 6 שעות לפני שהוא מתרחש',
    summary: 'Apple ו-Stanford Health פיתחו מודל למידת מכונה שמנתח נתוני ECG ו-PPG בזמן אמת ומסוגל לחזות אירוע פרפור לפני שהוא קורה.',
    content: 'המחקר שפורסם ב-The Lancet Digital Health כלל 45,000 משתמשי Apple Watch Ultra 2 בגילאי 45-80. מודל ה-AI, שאומן על 12 מיליון רשומות ECG, הצליח לזהות דפוסים עדינים המבשרים פרפור פרוזדורים בדיוק של 89% — 6 שעות בממוצע לפני האירוע.\n\nזה אומר שהמטופל מקבל התראה בשעון, שאומרת: "זוהו דפוסים חריגים בקצב הלב שלך — שקול לפנות לרופא." הנתונים מועברים אוטומטית לאפליקציית הבריאות.\n\nפרופ\' מרקו פרסקה מסטנפורד: "אנחנו עוברים מ-react ל-predict. במקום לאבחן אחרי שהנזק נעשה, אנחנו מצליחים לראות את הבעיה מתפתחת ולמנוע אותה."',
    category: 'health',
    imageUrl: 'https://images.unsplash.com/photo-1510017803350-4f6e2d04484f?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.5,
    scientificConfidence: 9,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "6 דק' קריאה",
    author: 'פרופ\' מרקו פרסקה',
    source: 'MobiHealthNews',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת הלב וכלי הדם', 'קצב הלב ופרפור פרוזדורים', 'רפואה מונעת'],
    timeline: [
      { id: 'ecg-tl1', title: 'פרסום תוצאות ב-Lancet', description: 'Apple ו-Stanford מפרסמים תוצאות הניסוי.', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ──────────────── 4-7 DAYS AGO ────────────────
  {
    id: 'cold-plunge-inflammation',
    title: 'מחקר חדש: טבילה בקרח (Cold Plunge) מפחיתה מדדי דלקת כרונית ב-37% — אבל רק בפרוטוקול מדויק',
    summary: 'חוקרי אוניברסיטת קופנהגן מצאו שהשפעת ה-Cold Exposure תלויה בצורה דרמטית בטמפרטורה, משך הזמן ותדירות הטבילה. לא כל cold plunge נוצר שווה.',
    content: 'במחקר הגדול ביותר שנעשה עד כה על השפעת הקור על מדדי דלקת (120 משתתפים, 12 שבועות), נמצא שהפרוטוקול האופטימלי הוא: מים ב-10-12°C, טבילה של 2-4 דקות, 3-4 פעמים בשבוע.\n\nבפרוטוקול הזה, רמות CRP (סמן דלקתי) ירדו ב-37%, IL-6 ירד ב-28%, וחלבוני דלקת נוספים ירדו באופן מובהק. לעומת זאת, טבילות קצרות מדי (פחות מדקה) או ארוכות מדי (מעל 6 דקות) לא הראו שיפור מובהק.\n\n"זו ההוכחה שהביו-האקינג דורש מדע, לא רק תחושות," אמרה ד"ר סוזנה סוברג, ראשת המחקר.',
    category: 'body',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.9,
    scientificConfidence: 9,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "5 דק' קריאה",
    author: 'ד"ר סוזנה סוברג',
    source: 'Longevity Tech',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת החיסון', 'תגובה דלקתית', 'מערכת העצבים הסימפתטית'],
    timeline: [
      { id: 'cold-tl1', title: 'פרסום תוצאות מחקר הקור', description: 'המחקר פורסם ב-Journal of Applied Physiology.', timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },
  {
    id: 'zone-2-cardio-longevity',
    title: 'אימוני Zone 2: המדע שמאחורי "הכושר ההולך" שמאריך חיים ב-10 שנים בממוצע',
    summary: 'מחקר אורך של 15 שנה בקרב 420,000 אנשים מראה שאימון אירובי במתח נמוך-בינוני (Zone 2) הוא היעיל ביותר להארכת תוחלת החיים — אפילו יותר מריצות מרתון.',
    content: 'הנתונים מהמחקר הגדול מפנסילבניה (420,000 משתתפים, 15 שנות מעקב) חד-משמעיים: אנשים שביצעו 150+ דקות שבועיות של אימון Zone 2 (60-70% מדופק מקסימלי) חיו בממוצע 10.2 שנים יותר מאנשים לא פעילים, ו-4.6 שנים יותר מאלה שרק ביצעו אימונים אינטנסיביים.\n\nהסיבה? Zone 2 הוא הטווח האופטימלי לשיפור יעילות המיטוכונדריות. באימון הזה, התאים לומדים לשרוף שומן במקום סוכר, מה שמפחית את העמסה על הלבלב ומשפר את הרגישות לאינסולין.\n\nד"ר פיטר אטיה: "אם הייתי צריך לבחור תרופה אחת לאריכות ימים, זה היה Zone 2 training."',
    category: 'sports',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.2,
    scientificConfidence: 9.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "7 דק' קריאה",
    author: 'ד"ר פיטר אטיה',
    source: 'Fitt Insider',
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת הלב וכלי הדם', 'תפקוד המיטוכונדריה', 'מטבוליזם שומנים'],
    timeline: [
      { id: 'zone2-tl1', title: 'פרסום מחקר אורך 15 שנים', description: 'המחקר פורסם ב-JAMA.', timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ──────────────── 1-2 WEEKS AGO ────────────────
  {
    id: 'protein-timing-myth',
    title: 'המיתוס של "חלון החלבון" נשבר: מטא-אנליזה חדשה מוכיחה שתזמון לא משנה',
    summary: '40 מחקרים, 1,800 ספורטאים, תשובה אחת: הכמות הכוללת של חלבון ביום חשובה הרבה יותר מתזמון הצריכה סביב האימון. "חלון ה-30 דקות" הוא מיתוס.',
    content: 'המטא-אנליזה שפורסמה ב-Sports Medicine Review סקרה 40 מחקרים RCT ומצאה שאין הבדל מובהק בבניית מסת שריר בין ספורטאים שצרכו חלבון מיד אחרי אימון לבין אלה שצרכו אותו 3-4 שעות מאוחר יותר.\n\nמה כן חשוב? הכמות הכוללת: 1.6-2.2 גרם חלבון לק"ג משקל גוף ביום, מחולקת ל-3-5 ארוחות. זה כל מה שנדרש להיפרטרופיה אופטימלית.\n\nד"ר אלן ארגון, חוקר תזונת ספורט: "30 שנות תעשיית תוספי מזון בנו מיתוס שלא מבוסס על מדע. הגיע הזמן לשחרר ספורטאים מהלחץ לשתות שייק 30 שניות אחרי האימון."',
    category: 'nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2c1cf?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.7,
    scientificConfidence: 9,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'ד"ר אלן ארגון',
    source: 'ScienceDaily',
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת השריר-שלד', 'סינתזת חלבון', 'היפרטרופיה'],
    timeline: [
      { id: 'prot-tl1', title: 'פרסום מטא-אנליזה', description: '40 מחקרים נסקרו ב-Sports Medicine Review.', timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },
  {
    id: 'microbiome-personalized-diet',
    title: 'סטארטאפ ישראלי: DayTwo פותחת פלטפורמה שבונה תפריט אישי לפי הרכב חיידקי המעי',
    summary: 'פלטפורמת AI שמנתחת את DNA חיידקי המעי של המשתמש ומייצרת תפריט מותאם אישית שמאזן סוכר, מפחית דלקת ומשפר עיכול.',
    content: 'DayTwo, סטארטאפ ישראלי שגייס 100 מיליון דולר, חשפה את הפלטפורמה החדשה שמשלבת סיקוונס גנטי של מיקרוביום המעי עם מודל AI שאומן על 200,000 פרופילים. התוצאה: תפריט יומי מותאם אישית שמנבא בדיוק של 85% את התגובה הגליקמית של כל מזון.\n\n"שני אנשים שאוכלים את אותו בננה יכולים לקבל תגובת סוכר שונה לחלוטין," מסביר פרופ\' ערן סגל מהטכניון. "המיקרוביום הוא המפתח — ועכשיו יש לנו את הכלים למפות אותו ולהשתמש בו."\n\nבניסוי בקרב 5,000 משתמשים, אלה שעקבו אחרי ההמלצות חוו ירידה ממוצעת של 22% ברמות סוכר אחרי ארוחה, ושיפור של 35% בסימפטומי נפיחות ועיכול.',
    category: 'nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.0,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'פרופ\' ערן סגל',
    source: 'הידען',
    publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['קהילת המיקרוביום במעי', 'מערכת העיכול', 'ויסות סוכר בדם'],
    timeline: [
      { id: 'dt-tl1', title: 'השקת פלטפורמת DayTwo', description: 'הפלטפורמה הושקה בישראל ובארה"ב.', timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ──────────────── 2-3 WEEKS AGO ────────────────
  {
    id: 'nad-supplement-trial',
    title: 'תוסף NMN (ניקוטינאמיד מונונוקלאוטיד) מגביר רמות NAD+ ב-68% — אבל ההשפעות משתנות',
    summary: 'ניסוי קליני חדש מ-Longevity Technology מדגים עלייה דרמטית ברמות NAD+ בדם, אך מדגיש שהתגובה הפיזיולוגית שונה מאוד בין אנשים בגילאים ומצבים רפואיים שונים.',
    content: 'הניסוי כלל 200 משתתפים בגילאי 40-70 שנטלו 500 מ"ג NMN ליום במשך 90 יום. רמות NAD+ בדם עלו בממוצע ב-68%, אך — ופה ההפתעה — ההשפעות הפיזיולוגיות נעו בין שיפור דרמטי באנרגיה וריכוז (40% מהמשתתפים) לבין כמעט שום שינוי מורגש (25% מהמשתתפים).\n\nהחוקרים זיהו שגורמים כמו רמת כושר בסיסית, הרכב גנטי של אנזימי NAD ותזונה משפיעים מאוד על התגובה.',
    category: 'body',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.8,
    scientificConfidence: 8.5,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "5 דק' קריאה",
    author: 'צוות Longevity Tech',
    source: 'Longevity Tech',
    publishedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['אנרגיה תאית (NAD+)', 'תפקוד המיטוכונדריה', 'הזדקנות תאית'],
    timeline: [
      { id: 'nmn-tl1', title: 'השלמת ניסוי 90 ימים', description: 'פורסמו תוצאות ביניים.', timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },
  {
    id: 'smart-insole-running',
    title: 'מדרסים חכמים של Nurvv מזהים טעויות בטכניקת ריצה ומפחיתים פציעות ברכיים ב-40%',
    summary: 'הטכנולוגיה הלבישה החדשה מודדת 32 נקודות לחץ בכף הרגל בזמן אמת ומספקת משוב שמתקן דפוסי נחיתה לקויים — לפני שהם הופכים לפציעה.',
    content: 'Nurvv Run, חברת טכנולוגיית ריצה בריטית, הציגה את דור המדרסים החכמים החדש עם 32 חיישני לחץ. במחקר עם 800 רצים, אלה שהשתמשו במדרסים וקיבלו משוב בזמן אמת (דרך האוזניות) חוו 40% פחות פציעות ברכיים ו-35% פחות כאבי שוקיים.\n\nהמערכת מזהה קדנס נמוך, נחיתה על עקב במקום אמצע כף הרגל, וחוסר סימטריה בין רגל ימין לשמאל. "זה כמו מאמן ריצה שנמצא איתך בכל אימון," אמרה ד"ר אירנה סמית\' מאוניברסיטת באת\'.',
    category: 'sports',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-bd45ba8fcf9b?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.5,
    scientificConfidence: 8,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'צוות Fitt Insider',
    source: 'Fitt Insider',
    publishedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת השריר-שלד', 'מפרקי ברכיים ושוקיים', 'ביומכניקה של ריצה'],
    timeline: [
      { id: 'nurvv-tl1', title: 'פרסום מחקר 800 רצים', description: 'התוצאות הוצגו בכנס הביומכניקה הבינלאומי.', timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ──────────────── 3-4 WEEKS AGO ────────────────
  {
    id: 'sleep-optimization-eight',
    title: 'Eight Sleep Pod 4 Ultra: המזרן החכם שמשפר שינה עמוקה ב-46% ומקצר זמן הירדמות ב-11 דקות',
    summary: 'הדור החדש של מזרן Eight Sleep משלב ויסות טמפרטורה אוטומטי, מעקב שינה רפואי ואלגוריתם AI שלומד את דפוסי השינה האישיים.',
    content: 'Eight Sleep Pod 4 Ultra הוא בלי ספק המוצר המרשים ביותר בתחום טכנולוגיית השינה. המזרן מחמם ומקרר כל צד של המיטה באופן עצמאי, מ-12°C ועד 46°C, ומשנה טמפרטורה לאורך הלילה בהתאם לשלבי השינה.\n\nבמחקר עם 2,000 משתמשים, זמן ההירדמות ירד ב-11 דקות בממוצע, שינה עמוקה (N3) עלתה ב-46%, ומספר ההתעוררויות הלילות ירד ב-32%.\n\nMatt Walker, חוקר שינה מברקלי: "שינה היא הפעולה הבודדת הכי חשובה שאנחנו יכולים לעשות לבריאות. וטמפרטורה היא הגורם מספר 1 שמשפיע על איכות השינה."',
    category: 'health',
    imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.8,
    scientificConfidence: 8,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'צוות Athletech News',
    source: 'Athletech News',
    publishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת השינה', 'ויסות טמפרטורה', 'שיקום תאי ושיפור קוגניטיבי'],
    timeline: [
      { id: 'eight-tl1', title: 'השקת Pod 4 Ultra', description: 'Eight Sleep הכריזה על הדור הרביעי.', timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },
  {
    id: 'red-light-therapy-skin',
    title: 'טיפול באור אדום (Red Light Therapy): מטא-אנליזה מגלה שיפור של 35% בייצור קולגן',
    summary: 'סקירה שיטתית של 45 מחקרים מוכיחה שחשיפה לאור אדום באורכי גל של 630-670nm משפרת מרקם עור, מפחיתה קמטים ומאיצה ריפוי פצעים.',
    content: 'המטא-אנליזה שפורסמה ב-Photobiomodulation, Photomedicine, and Laser Surgery סקרה 45 מחקרים עם 3,500 משתתפים. המסקנה: טיפול באור אדום (630-670nm) ב-10-20 דקות ביום, 4-5 פעמים בשבוע, מוביל לשיפור של 35% בייצור קולגן, 28% שיפור באלסטיות העור ו-40% האצה בריפוי פצעים.\n\nהאור האדום חודר 5-10 מ"מ לתוך העור ומשפעל את המיטוכונדריות בתאים, מה שמגביר ייצור ATP ומאיץ תהליכי תיקון תאי.',
    category: 'body',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.6,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'ד"ר מייקל המבלין',
    source: 'Medical News Today',
    publishedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['עור ורקמת חיבור', 'סינתזת קולגן', 'תפקוד המיטוכונדריה'],
    timeline: [
      { id: 'rlt-tl1', title: 'פרסום מטא-אנליזה', description: '45 מחקרים נסקרו.', timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ──────────────── 5-6 WEEKS AGO ────────────────
  {
    id: 'magnesium-threonate-sleep',
    title: 'מגנזיום L-Threonate: התוסף היחיד שעובר את מחסום הדם-מוח ומשפר שינה ב-27%',
    summary: 'מחקר חדש מדגים את ההבדל הדרמטי בין סוגי מגנזיום: רק L-Threonate חוצה את מחסום הדם-מוח ומגיע ישירות לתאי עצב, עם שיפור מדיד באיכות השינה.',
    content: 'פרופ\' גוהוה ליו מ-MIT, שפיתחה את מגנזיום L-Threonate, פרסמה מחקר חדש ב-Frontiers in Neuroscience עם 300 משתתפים. הממצא המרכזי: L-Threonate העלה רמות מגנזיום במוח ב-42% (לעומת 3% בלבד עם מגנזיום ציטראט), מה שהוביל לשיפור של 27% באיכות השינה ו-19% בזיכרון לטווח קצר.\n\n"הבעיה עם רוב תוספי המגנזיום היא שהם לא מגיעים למוח," הסבירה פרופ\' ליו. "95% מהמגנזיום שנבלע נשאר בגוף ולא עובר את מחסום הדם-מוח. L-Threonate הוא היוצא מן הכלל."',
    category: 'nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=1200&q=80',
    impactScore: 8.4,
    scientificConfidence: 9,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "5 דק' קריאה",
    author: 'פרופ\' גוהוה ליו',
    source: 'ScienceDaily',
    publishedAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת העצבים המרכזית', 'מערכת השינה', 'זיכרון וקוגניציה'],
    timeline: [
      { id: 'mag-tl1', title: 'פרסום מחקר MIT', description: 'המחקר פורסם ב-Frontiers in Neuroscience.', timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },
  {
    id: 'crispr-hearing-loss',
    title: 'CRISPR לראשונה בבן אדם: ילד בן 11 שומע לראשונה בחייו לאחר עריכה גנטית',
    summary: 'בפריצת דרך היסטורית, רופאי בית החולים בפילדלפיה ביצעו טיפול CRISPR שתיקן מוטציה גנטית בעצב השמיעה — וילד שנולד חירש שומע לראשונה.',
    content: 'איידן, בן 11, נולד עם חירשות מלאה בשתי האוזניים בגלל מוטציה בגן OTOF. הגן הזה מקודד לחלבון שנקרא אוטופרלין, שאחראי להעברת אותות קוליים מתאי השמיעה בשבלול לעצב. בלעדיו — שקט מוחלט.\n\nצוות רפואי בפילדלפיה הזריק לשבלול האוזן של איידן וקטור AAV נושא את הגן OTOF התקין. תוך 6 שבועות, איידן התחיל לשמוע לראשונה. עכשיו, 6 חודשים אחרי, הוא מנהל שיחות בטלפון.\n\n"הרגע שהוא אמר \'אמא\' בפעם הראשונה — כל הצוות בכה," סיפרה ד"ר ג\'ון ג\'רמילו, ראשת הצוות.',
    category: 'body',
    imageUrl: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.8,
    scientificConfidence: 9.5,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "6 דק' קריאה",
    author: 'ד"ר ג\'ון ג\'רמילו',
    source: 'Lifespan.io',
    publishedAt: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת השמיעה', 'עריכה גנטית (CRISPR)', 'עצבים קרניאליים'],
    timeline: [
      { id: 'crispr-tl1', title: 'ביצוע הטיפול הגנטי', description: 'הטיפול בוצע בבית החולים בפילדלפיה.', timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString() },
      { id: 'crispr-tl2', title: 'איידן שומע לראשונה', description: '6 שבועות אחרי הטיפול, הילד מתחיל לשמוע.', timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ──────────────── 6 WEEKS AGO ────────────────
  {
    id: 'sauna-cardiovascular',
    title: 'סאונה פינית 4 פעמים בשבוע מפחיתה סיכון לאירוע לב ב-50% — מחקר 20 שנות מעקב',
    summary: 'מחקר פיני ארוך טווח בקרב 2,300 גברים מוכיח שחשיפה קבועה לחום גבוה (80-100°C) היא אחת ההתערבויות היעילות ביותר לבריאות הלב וכלי הדם.',
    content: 'מחקר Kuopio Ischemic Heart Disease Risk Factor Study עקב אחרי 2,315 גברים פינים במשך 20 שנה. הממצא: אלה ששהו בסאונה 4-7 פעמים בשבוע חוו הפחתה של 50% בסיכון למוות מאירוע לב, בהשוואה לאלה שביקרו פעם בשבוע.\n\nהמנגנון: חשיפה לחום גורמת לשחרור heat shock proteins שמגנים על הלב, מפחיתה לחץ דם ומשפרת תפקוד אנדותל כלי הדם.\n\nד"ר ג\'ארי לאוקנן, ראש המחקר: "סאונה היא בעצם \'אימון קרדיו פסיבי\' — הגוף מגיב לחום כמו שהוא מגיב לאימון. ולפעמים זה אפילו יעיל יותר."',
    category: 'health',
    imageUrl: 'https://images.unsplash.com/photo-1555708982-8645ec9ce3cc?auto=format&fit=crop&w=1200&q=80',
    impactScore: 9.0,
    scientificConfidence: 9.5,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "5 דק' קריאה",
    author: 'ד"ר ג\'ארי לאוקנן',
    source: 'הידען',
    publishedAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
    physiologicalImpact: ['מערכת הלב וכלי הדם', 'heat shock proteins', 'לחץ דם ואנדותל'],
    timeline: [
      { id: 'sauna-tl1', title: 'פרסום ממצאי 20 שנות מעקב', description: 'המחקר פורסם ב-JAMA Internal Medicine.', timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString() }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WELLWORTHY.COM — תוכן מתורגם מהחודשיים האחרונים (יוני-אוגוסט 2026)
  // ═══════════════════════════════════════════════════════════════════════

  // ──── אוגוסט 2026 ────
  {
    id: 'ww-ultrahuman-emerald-ai',
    title: 'Ultrahuman משיקה עדכון אפליקציה חסר תקדים: AI שהופך נתוני בריאות להנחיות יומיות',
    summary: 'מערכת ה-AI החדשה Emerald מנתחת את נתוני השינה, ההתאוששות והפעילות שלך ומספקת המלצות מותאמות אישית — מה לעשות, מתי לאכול ואיך להתאמן.',
    content: 'Ultrahuman חשפה את השדרוג הגדול ביותר לאפליקציה שלה עם השקת Emerald AI — מנוע בינה מלאכותית שמנתח את כל הנתונים הפיזיולוגיים שנאספים מטבעת ה-Ultrahuman Ring וסנסור הגלוקוז M2 Live, ומייצר תוכנית פעולה יומית מותאמת אישית.\n\nבמקום רק להציג גרפים, Emerald אומרת לך: "היום כדאי לעשות אימון Zone 2 של 40 דקות" או "השינה שלך אמש הייתה חלשה — תעדיף הליכה קלה על אימון כוח." המערכת לומדת את הדפוסים האישיים שלך ומשתפרת עם הזמן.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/08/ultrahuman-emerald-2.png',
    impactScore: 9.1,
    scientificConfidence: 8,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-08-07T17:58:49Z',
    lastUpdated: '2026-08-07T17:58:49Z',
    physiologicalImpact: ['בינה מלאכותית ובריאות', 'שינה והתאוששות', 'ניטור גלוקוז'],
    timeline: [{ id: 'ww-ult1', title: 'השקת Emerald AI', description: 'Ultrahuman חשפה את מנוע ה-AI החדש.', timestamp: '2026-08-07T17:58:49Z' }]
  },
  {
    id: 'ww-whoop-natural-cycles',
    title: 'WHOOP משלבת את אפליקציית הפריון Natural Cycles — ללא עלות נוספת למנויים',
    summary: 'WHOOP מציעה כעת שנה חינם של אפליקציית Natural Cycles (בעלת אישור FDA) למעקב פריון ומניעת הריון — ישירות מנתוני הצמיד.',
    content: 'בצעד שמחבר בין טכנולוגיית כושר לבריאות רבייתית, WHOOP הכריזה על שותפות עם Natural Cycles — אפליקציית מניעת הריון/מעקב פריון היחידה עם אישור FDA. המנויים יקבלו גישה חינמית לשנה מלאה.\n\nהחיבור מאפשר ל-Natural Cycles לקרוא נתוני טמפרטורת עור, HRV ודפוסי שינה ישירות מצמיד WHOOP, מה שמשפר משמעותית את דיוק הניבוי לעומת מדידת טמפרטורה ידנית בלבד.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/08/whoop-natural-cycles.jpg',
    impactScore: 8.5,
    scientificConfidence: 9,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-08-06T15:00:00Z',
    lastUpdated: '2026-08-06T15:00:00Z',
    physiologicalImpact: ['בריאות רבייתית', 'מעקב פריון', 'הורמונים ומחזור'],
    timeline: [{ id: 'ww-whoop1', title: 'הכרזה על שותפות WHOOP + Natural Cycles', description: 'מנויי WHOOP מקבלים גישה חינם.', timestamp: '2026-08-06T15:00:00Z' }]
  },
  {
    id: 'ww-casio-ring-watch',
    title: 'Casio מכניסה מעקב בריאות לשעון הטבעת המיניאטורי שלה — דופק, שינה וחמצן בדם',
    summary: 'דגם CRW-H001M מוסיף מדידת דופק, רוויית חמצן בדם, מעקב שינה ופעילות גופנית — הכל בטבעת-שעון זעירה על האצבע.',
    content: 'Casio, שכבר הפתיעה את העולם עם שעון טבעת מכני, עכשיו מוסיפה חיישנים בריאותיים. הדגם החדש CRW-H001M-8 כולל חיישן PPG למדידת דופק רציף, רוויית חמצן בדם (SpO2), מעקב שינה אוטומטי וספירת צעדים.\n\nזו תשובה ישירה ל-Oura ו-Samsung Galaxy Ring, אבל עם יתרון ייחודי — הטבעת גם מציגה שעה! המחיר צפוי להיות תחרותי משמעותית.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/08/CASIO-smart-ring.jpg',
    impactScore: 8.3,
    scientificConfidence: 7,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-08-05T14:00:00Z',
    lastUpdated: '2026-08-05T14:00:00Z',
    physiologicalImpact: ['מעקב דופק', 'רוויית חמצן', 'מעקב שינה'],
    timeline: [{ id: 'ww-casio1', title: 'חשיפת שעון הטבעת החכם של Casio', description: 'Casio מוסיפה חיישני בריאות לטבעת-השעון.', timestamp: '2026-08-05T14:00:00Z' }]
  },
  {
    id: 'ww-hatch-sleep-clock',
    title: 'Hatch השיקה שעון שינה חדש שעוקב אחרי השינה שלך — בלי לתת לך ציון לילי',
    summary: 'המכשיר ליד המיטה עוקב אחרי דפוסי השינה שלך ללא צורך בלביש, תוך בניית הרגלים טובים יותר — בלי חרדת הציון.',
    content: 'Hatch, שהפכה מוכרת בזכות מנורת השינה הפופולרית Restore, משיקה מכשיר חדש: שעון שינה שמשתמש בטכנולוגיית רדאר לזהות תנועות ונשימה בשינה — ללא צורך ללבוש שעון או טבעת.\n\nבניגוד למתחרים, Hatch בחרה בכוונה לא להציג "ציון שינה" — גישה שלדעתם יוצרת יותר חרדה מתועלת. במקום זאת, האפליקציה מציגה תובנות וטיפים מעשיים: "אתמול נרדמת ב-23:15, מהר ב-12 דקות מהממוצע שלך."',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/08/hatch-sleep-clock.webp',
    impactScore: 8.2,
    scientificConfidence: 7.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-08-04T14:00:00Z',
    lastUpdated: '2026-08-04T14:00:00Z',
    physiologicalImpact: ['מעקב שינה', 'הרגלי שינה', 'טכנולוגיית רדאר'],
    timeline: [{ id: 'ww-hatch1', title: 'השקת שעון השינה של Hatch', description: 'מכשיר שעוקב שינה ללא לביש.', timestamp: '2026-08-04T14:00:00Z' }]
  },
  {
    id: 'ww-nike-hyrox-hybrid',
    title: 'Nike משיקה מערכת נעליים היברידית חדשה לאימוני Hyrox — ריצה + הרמות באותה נעל',
    summary: 'הדגמים Hybrid Fly ו-Hybrid RN נבנו לכל דבר — מריצת אינטרוולים ועד הרמות כבדות, בנעל אחת.',
    content: 'Nike השיקה את מערכת הנעליים ההיברידית הראשונה שלה, שמיועדת ספציפית לתחרויות ואימוני Hyrox — הדיסציפלינה שמשלבת ריצה עם תרגילי כוח פונקציונליים.\n\nHybrid Fly מיועדת לספורטאים שמעדיפים מהירות (סוליית קרבון + ריפוד React), בעוד Hybrid RN מתאימה יותר לאימוני כוח (סוליה שטוחה יותר עם אחיזה מוגברת). שתיהן עוברות בצורה חלקה בין ריצה, גרירת משקולות ודחיפת מזחלת.',
    category: 'sports',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/08/Nike-Hybrid--scaled.jpg',
    impactScore: 7.8,
    scientificConfidence: 7,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-08-03T14:00:00Z',
    lastUpdated: '2026-08-03T14:00:00Z',
    physiologicalImpact: ['ביומכניקה', 'אימון היברידי', 'ספורט פונקציונלי'],
    timeline: [{ id: 'ww-nike1', title: 'השקת Nike Hybrid', description: 'Nike נכנסת לשוק ה-Hyrox.', timestamp: '2026-08-03T14:00:00Z' }]
  },

  // ──── יולי 2026 ────
  {
    id: 'ww-spotify-running-mode',
    title: 'Spotify משיקה מצב ריצה חדש שבונה פלייליסט מותאם אישית סביב האימון שלך',
    summary: 'הפיצ\'ר יוצר פלייליסטים מותאמים בזמן אמת על פי סגנון הריצה, הקצב המועדף, סוג המוזיקה ואורך האימון.',
    content: 'Spotify הכריזה על Running Mode — פיצ\'ר חדש שמנתח את דפוסי הריצה שלך ומייצר פלייליסט אוטומטי שמתאים לקצב הרגליים. אם אתה רץ ב-170 BPM, המוזיקה תתאים לקצב הזה.\n\nהמערכת לומדת לאורך זמן מה אתה מעדיף — טראנס בריצות ארוכות, היפ-הופ באינטרוולים — ומשפרת את ההמלצות. "מוזיקה היא חלק בלתי נפרד מאימון ריצה," אמר סמנכ"ל המוצר. "עכשיו היא מותאמת בזמן אמת."',
    category: 'sports',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/spotify-run.webp',
    impactScore: 7.5,
    scientificConfidence: 6,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-31T14:00:00Z',
    lastUpdated: '2026-07-31T14:00:00Z',
    physiologicalImpact: ['מוטיבציה ואימון', 'קצב ריצה', 'טכנולוגיית ספורט'],
    timeline: [{ id: 'ww-spot1', title: 'השקת Spotify Running Mode', description: 'פלייליסטים אוטומטיים לפי קצב ריצה.', timestamp: '2026-07-31T14:00:00Z' }]
  },
  {
    id: 'ww-ag1-pro',
    title: 'AG1 משיקה את AG1 Pro — תוסף שמשלב בריאות מעיים, כוח שרירי ותזונה יומית בכפית אחת',
    summary: 'הנוסחה החדשה מוסיפה רכיבים קליניים לביצועי שרירים תוך שימור ליבת התזונה היומית של AG1.',
    content: 'AG1 (לשעבר Athletic Greens) השיקה את AG1 Pro — גרסה מתקדמת שמשלבת את 75 הרכיבים של AG1 Next Gen עם תוספת קריאטין מונוהידראט, HMB (hydroxymethylbutyrate) ו-Creapure לתמיכה בכוח שרירי ובשיקום.\n\nלטענת החברה, מדובר ב"הכל-באחד" האמיתי — תזונה יומית, פרוביוטיקה, תמיכה קוגניטיבית ועכשיו גם ביצועי שרירים. המחיר: $129 לחודש.',
    category: 'nutrition',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/ag1-pro-e1785522863713.png',
    impactScore: 8.0,
    scientificConfidence: 7.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-30T14:00:00Z',
    lastUpdated: '2026-07-30T14:00:00Z',
    physiologicalImpact: ['תזונת ספורט', 'בריאות המעי', 'כוח שרירי'],
    timeline: [{ id: 'ww-ag1', title: 'השקת AG1 Pro', description: 'שילוב שרירים + מעיים בתוסף אחד.', timestamp: '2026-07-30T14:00:00Z' }]
  },
  {
    id: 'ww-nike-hyperice-hyperslide',
    title: 'Nike x Hyperice: נעלי ה-Hyperslide משתמשות ברטט וחום לשיקום ספורטאים ב-5 דקות',
    summary: 'הנעליים החדשות משלבות טכנולוגיית רטט וחום של Hyperice עם עיצוב Nike — שיקום מהיר בין סטים, ספרינטים ותרגילים.',
    content: 'שותפות Nike x Hyperice ממשיכה עם Air Zoom Hyperslide — נעל שיקום שמשלבת מנועי רטט ואלמנטי חימום בתוך הסוליה. הספורטאי פשוט נועל אותן בין סטים או אחרי אימון, ו-5 דקות מספיקות לשיפור זרימת דם ושחרור מתח שרירי.\n\nהטכנולוגיה מבוססת על מחקרי Hyperice שמדגימים כי שילוב רטט + חום מאיץ סילוק חומצת חלב ב-30% בהשוואה למנוחה פסיבית.',
    category: 'sports',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/air-zoom-hyperslide.png',
    impactScore: 8.4,
    scientificConfidence: 8,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-27T14:00:00Z',
    lastUpdated: '2026-07-27T14:00:00Z',
    physiologicalImpact: ['שיקום שרירי', 'זרימת דם', 'סילוק חומצת חלב'],
    timeline: [{ id: 'ww-hyper1', title: 'השקת Nike x Hyperice Hyperslide', description: 'נעלי שיקום עם רטט וחום.', timestamp: '2026-07-27T14:00:00Z' }]
  },
  {
    id: 'ww-garmin-cirqa',
    title: 'Garmin נכנסת למרוץ עוקבי הכושר ללא מסך עם השקת Cirqa',
    summary: 'הצמיד עוקב אחרי שינה, התאוששות ונתוני מחזור חודשי 24/7 — ללא מנוי חודשי.',
    content: 'Garmin הציגה את Cirqa — צמיד כושר ללא מסך שמתחרה ישירות ב-WHOOP וב-Amazon Halo. הצמיד מודד דופק, HRV, רוויית חמצן, שינה וגם מעקב מחזור חודשי — הכל 24 שעות ביממה.\n\nהיתרון הגדול: אין מנוי חודשי. בעוד WHOOP גובה $30/חודש, Garmin Cirqa הוא רכישה חד-פעמית. סוללה ל-5 ימים, עמידות במים ועיצוב מינימליסטי.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/Garmin-CIRQA.png',
    impactScore: 8.6,
    scientificConfidence: 8,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-22T14:00:00Z',
    lastUpdated: '2026-07-22T14:00:00Z',
    physiologicalImpact: ['מעקב דופק ו-HRV', 'שינה', 'בריאות נשים'],
    timeline: [{ id: 'ww-garmin1', title: 'השקת Garmin Cirqa', description: 'צמיד ללא מסך וללא מנוי.', timestamp: '2026-07-22T14:00:00Z' }]
  },
  {
    id: 'ww-cold-plunge-guide',
    title: 'המדריך המלא לרכישת אמבט קרח: כל מה שחייבים לדעת לפני שמוציאים כסף',
    summary: 'עלות כוללת, תחזוקה, טמפרטורות, ודברים שאף מותג לא יגיד לכם — המדריך הכי מקיף לטבילות קרח.',
    content: 'Wellworthy פרסמו את המדריך הכי מקיף שנכתב על רכישת Cold Plunge. הנקודות המרכזיות: עלות כוללת נעה בין $3,000 ל-$10,000 כולל חשמל ותחזוקה, צריך להחליף מסנן כל 3 חודשים, והטמפרטורה האופטימלית למתחילים היא 12-15°C (לא 2°C כמו שמשפיענים מציגים).\n\nהמדריך גם חושף שרוב האנשים מפסיקים להשתמש תוך 3 חודשים — בעיקר בגלל תחזוקה ולא בגלל הקור.',
    category: 'body',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/coldtub-1024x737.png',
    impactScore: 7.8,
    scientificConfidence: 7,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-20T14:00:00Z',
    lastUpdated: '2026-07-20T14:00:00Z',
    physiologicalImpact: ['חשיפה לקור', 'מערכת החיסון', 'שיקום'],
    timeline: [{ id: 'ww-cold1', title: 'פרסום מדריך Cold Plunge', description: 'המדריך המלא ביותר לטבילות קרח.', timestamp: '2026-07-20T14:00:00Z' }]
  },
  {
    id: 'ww-sonata-preventive',
    title: 'Sonata: מנוי רפואי חדש שמשלב סיקוונס גנומי מלא עם רופא אישי לרפואה מונעת',
    summary: 'Sonata משלבת סיקוונס גנום מלא ובדיקות גיל ביולוגי עם רופא שעוקב אחרי הבריאות שלך לאורך זמן.',
    content: 'Sonata היא מנוי רפואי מסוג חדש שמשלב: סיקוונס גנום מלא (whole-genome sequencing), בדיקות גיל ביולוגי (אפיגנטיות), פאנל דם מורחב, ורופא אישי שמלווה אותך לאורך זמן.\n\nבמקום לחכות עד שנחלה, Sonata בונה פרופיל סיכונים גנטי ומפנה אותך לבדיקות ספציפיות מוקדם — הרבה לפני שמופיעים סימפטומים. המחיר: $4,900/שנה. "אנחנו הופכים את הרפואה מתגובתית למונעת," אמרה המייסדת.',
    category: 'body',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/SONATA.jpg',
    impactScore: 9.0,
    scientificConfidence: 9,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-15T14:00:00Z',
    lastUpdated: '2026-07-15T14:00:00Z',
    physiologicalImpact: ['גנומיקה', 'רפואה מונעת', 'גיל ביולוגי'],
    timeline: [{ id: 'ww-son1', title: 'השקת Sonata', description: 'מנוי רפואה מונעת עם סיקוונס גנום.', timestamp: '2026-07-15T14:00:00Z' }]
  },
  {
    id: 'ww-id-formulas-aging',
    title: 'Advanced ID טוענת לירידה של 5.2 שנים בגיל הביולוגי תוך 12 שבועות — עם אינטגרציית WHOOP',
    summary: 'פרוטוקול תוספים חדש שנמדד דרך אינטגרציה ראשונה מסוגה עם צמיד WHOOP, מראה ירידה דרמטית בגיל ביולוגי.',
    content: 'ID Formulas השיקה את Advanced ID — פרוטוקול תוספים שטוען להפחתת 5.2 שנים מהגיל הביולוגי תוך 12 שבועות. החידוש: אינטגרציה ישירה עם WHOOP שמאפשרת לעקוב אחרי מדדי HRV, שינה ודופק מנוחה כאינדיקטורים להשפעת הפרוטוקול.\n\nהפרוטוקול כולל: NMN, Spermidine, Trans-Resveratrol ו-Fisetin — מולקולות שקשורות למסלולי Sirtuins ו-autophagy. המחיר: $199/חודש.',
    category: 'body',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/Advanced-ID.png',
    impactScore: 8.7,
    scientificConfidence: 7,
    clinicalStage: 'ניסויים קליניים (בני אדם)',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-14T14:00:00Z',
    lastUpdated: '2026-07-14T14:00:00Z',
    physiologicalImpact: ['הזדקנות תאית', 'Sirtuins ו-autophagy', 'גיל ביולוגי'],
    timeline: [{ id: 'ww-id1', title: 'השקת Advanced ID', description: 'פרוטוקול נגד הזדקנות עם מעקב WHOOP.', timestamp: '2026-07-14T14:00:00Z' }]
  },
  {
    id: 'ww-sunlighten-sauna-pulseiq',
    title: 'סאונה חכמה של Sunlighten: אורכי גל מותאמים אישית + תוכניות בריאות מובנות',
    summary: 'הסאונה mPulse עם טכנולוגיית PulseIQ מאפשרת לכוונן אורכי גל של אינפרא-אדום לפי צרכי הגוף — שיקום, דטוקס או הפחתת כאב.',
    content: 'Sunlighten חשפה את הגרסה החדשה של סאונת ה-mPulse עם טכנולוגיית PulseIQ. בניגוד לסאונות אינפרא-אדום רגילות, PulseIQ מאפשרת לבחור בין שלושה אורכי גל: Near-IR (שיקום רקמות), Mid-IR (שיפור זרימת דם) ו-Far-IR (דטוקסיפיקציה).\n\nהסאונה כוללת תוכניות מובנות: "התאוששות מאימון" (35 דקות, Near + Mid), "שינה טובה יותר" (25 דקות, Far), "הפחתת כאב" (40 דקות, Near). כל תוכנית מתכווננת אוטומטית.',
    category: 'body',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/sunlighten-mpulse.webp',
    impactScore: 8.1,
    scientificConfidence: 7.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-09T14:00:00Z',
    lastUpdated: '2026-07-09T14:00:00Z',
    physiologicalImpact: ['אינפרא-אדום', 'שיקום רקמות', 'דטוקסיפיקציה'],
    timeline: [{ id: 'ww-sun1', title: 'השקת Sunlighten mPulse עם PulseIQ', description: 'סאונה חכמה עם אורכי גל מותאמים.', timestamp: '2026-07-09T14:00:00Z' }]
  },
  {
    id: 'ww-stripit-supplements',
    title: 'StripIt: סטארטאפ שמשיק תוספי מזון שנמסים על הלשון — ללא כדורים או מים',
    summary: 'רצועות Sleep ו-Digest נמסות תוך שניות על הלשון, ללא צורך בגלולות, מים או מיקסרים.',
    content: 'StripIt, סטארטאפ מלוס אנג\'לס, השיקה קו תוספי מזון חדשני בפורמט רצועות דקות שנמסות על הלשון. שתי מוצרים ראשונים: Sleep (מלטונין + L-theanine + מגנזיום) ו-Digest (פרוביוטיקה + אנזימי עיכול).\n\nהרצועות קטנות כמו מדבקה, נמסות תוך 10 שניות, ולא דורשות מים. "אנשים שונאים לבלוע גלולות," אומרת המייסדת. "זה הפורמט הכי נוח שקיים."',
    category: 'nutrition',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/07/StripIt.png',
    impactScore: 7.3,
    scientificConfidence: 6.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-07-06T14:00:00Z',
    lastUpdated: '2026-07-06T14:00:00Z',
    physiologicalImpact: ['תוספי מזון', 'שינה', 'עיכול'],
    timeline: [{ id: 'ww-strip1', title: 'השקת StripIt', description: 'תוספים שנמסים על הלשון.', timestamp: '2026-07-06T14:00:00Z' }]
  },

  // ──── יוני 2026 ────
  {
    id: 'ww-ultrahuman-m2-glucose',
    title: 'Ultrahuman M2 Live: ניטור גלוקוז ללא מרשם רופא — עכשיו זמין בארה"ב',
    summary: 'לראשונה אפשר לקנות סנסור גלוקוז רציף ללא מרשם ולחבר אותו לאימונים, שינה ותזונה.',
    content: 'Ultrahuman השיקה את M2 Live בארה"ב — סנסור גלוקוז רציף (CGM) שלא דורש מרשם רופא. המשמעות: כל אחד יכול לעקוב אחרי איך גוף שלו מגיב לאוכל, אימונים ושינה ברמת הגלוקוז.\n\nהחידוש: M2 Live מתחבר ישירות לטבעת Ultrahuman Ring ומציג תמונה מלאה — "אכלת פיצה, הגלוקוז זינק ל-180, שינה עמוקה ירדה ב-20%." מחיר: $299 ל-3 חודשי שימוש.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/Screenshot-2026-06-26-at-2.35.15-PM.png',
    impactScore: 9.2,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-26T14:00:00Z',
    lastUpdated: '2026-06-26T14:00:00Z',
    physiologicalImpact: ['ניטור גלוקוז', 'מטבוליזם', 'תזונה מותאמת'],
    timeline: [{ id: 'ww-m2-1', title: 'השקת M2 Live בארה"ב', description: 'ניטור גלוקוז ללא מרשם.', timestamp: '2026-06-26T14:00:00Z' }]
  },
  {
    id: 'ww-amazfit-helio-strap',
    title: 'Amazfit Helio Strap Pro: מערכת דו-חיישנית שמזיזה מעקב מהפרק ישירות לשריר',
    summary: 'שני חיישנים — אחד על היד ואחד על השוק — מודדים תנועה, יציבות ועומס על השרירים בזמן אמת.',
    content: 'Amazfit השיקה את Helio Strap Pro — מערכת חיישנים כפולה לאימוני Hyrox ו-CrossFit. במקום שעון בלבד, חיישן אחד על פרק כף היד וחיישן שני על השוק מודדים ביחד: סימטריה בין רגליים, עומס מפרקי, קדנס ריצה ואפילו עומס אקצנטרי על שריר הארבע ראשי.\n\n"זה המעבר מ-tracking ל-coaching," אמר סמנכ"ל המוצר של Amazfit. "אנחנו לא רק מספרים לך כמה קלוריות שרפת, אנחנו אומרים לך שהרגל השמאלית סופגת 15% יותר עומס."',
    category: 'sports',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/helio-strap-pro.webp',
    impactScore: 8.3,
    scientificConfidence: 7.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-24T14:00:00Z',
    lastUpdated: '2026-06-24T14:00:00Z',
    physiologicalImpact: ['ביומכניקה', 'עומס שרירי', 'אימון פונקציונלי'],
    timeline: [{ id: 'ww-amaz1', title: 'השקת Amazfit Helio Strap Pro', description: 'מערכת דו-חיישנית לספורטאים.', timestamp: '2026-06-24T14:00:00Z' }]
  },
  {
    id: 'ww-elysium-creatine-plus',
    title: 'Elysium Creatine+: קריאטין שפותח עם מומחה אריכות ימים מסטנפורד — לשרירים ולמוח',
    summary: 'פורמולה שפותחה בשיתוף מומחה לאריכות ימים מסטנפורד, משלבת קריאטין עם תמיכה קוגניטיבית ושיקום.',
    content: 'Elysium, חברת אריכות הימים שייסד ד"ר לאונרד גארנטה מ-MIT, השיקה Creatine+ — תוסף שמשלב קריאטין מונוהידראט עם רכיבים לתמיכה קוגניטיבית. הפורמולה פותחה בשיתוף ד"ר מייקל סנדר, מומחה אריכות ימים מסטנפורד.\n\nבניגוד לקריאטין רגיל, Creatine+ מוסיפה phosphatidylserine (לתמיכה בממברנות עצביות) ו-alpha-GPC (לייצור אצטילכולין). "קריאטין הוא לא רק לשרירים," אמר ד"ר סנדר. "המוח צורך 20% מאנרגיית הגוף, וקריאטין משפר את ייצור ה-ATP בנוירונים."',
    category: 'nutrition',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/creatine.jpg',
    impactScore: 8.5,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-23T14:00:00Z',
    lastUpdated: '2026-06-23T14:00:00Z',
    physiologicalImpact: ['אנרגיה תאית (ATP)', 'קוגניציה', 'שרירים'],
    timeline: [{ id: 'ww-ely1', title: 'השקת Elysium Creatine+', description: 'קריאטין + תמיכה קוגניטיבית.', timestamp: '2026-06-23T14:00:00Z' }]
  },
  {
    id: 'ww-midjourney-body-scan',
    title: 'Midjourney מפתחת סריקת גוף מלאה דמוית MRI שמתבצעת ב-60 שניות — בתוך ספא',
    summary: 'הקונספט מחליף מגנטים וקרינה בחיישנים תת-מימיים ופועל בסביבת ספא — סריקה מלאה בפחות מדקה.',
    content: 'Midjourney, הסטארטאפ שהפך מוכר בזכות יצירת תמונות AI, חשף פרויקט משנה משמעותי: מכשיר סריקת גוף מלאה שעובד בתוך אמבט מים. במקום שדות מגנטיים (MRI) או קרני רנטגן, המערכת משתמשת ברשת חיישנים אולטראסאונדיים ואופטיים מתחת למים.\n\nהמטופל שוכב באמבט ל-60 שניות, והמערכת מייצרת מודל תלת-ממדי של כל איברי הגוף. "אנחנו רוצים שסריקת גוף תהיה כמו ביקור בספא, לא כמו ביקור בבית חולים," אמר דיוויד הולץ, מייסד Midjourney.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/Screenshot-2026-06-19-at-1.08.06-PM-scaled.png',
    impactScore: 9.3,
    scientificConfidence: 6,
    clinicalStage: 'מחקר תיאורטי',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-19T14:00:00Z',
    lastUpdated: '2026-06-19T14:00:00Z',
    physiologicalImpact: ['דימות רפואי', 'אבחון מוקדם', 'חדשנות רפואית'],
    timeline: [{ id: 'ww-mid1', title: 'חשיפת פרויקט סריקת הגוף של Midjourney', description: 'סריקה תת-מימית ב-60 שניות.', timestamp: '2026-06-19T14:00:00Z' }]
  },
  {
    id: 'ww-muscle-loss-30s',
    title: 'איבוד שריר מתחיל בגיל 30 — ושגרת הקרדיו שלך עלולה להחמיר את המצב',
    summary: 'למה אימוני קרדיו ארוכים ומתישים מוחלפים בתכנות כוח חכם יותר. Sarcopenia מתחילה מוקדם ממה שחשבת.',
    content: 'מאמר חשוב מ-Wellworthy שמסביר למה אנשים בגילאי 30-50 צריכים לשנות גישה: sarcopenia (איבוד מסת שריר) מתחילה כבר בגיל 30, בקצב של 3-8% לעשור. אם כל מה שאתה עושה זה ריצה, הליכה או רכיבה — אתה מאיץ את התהליך.\n\n"אימוני כוח 3-4 פעמים בשבוע הם לא אופציה — הם חובה ביולוגית," כותבת המאמר. "קרדיו ארוך שמעלה קורטיזול ושורף שריר הוא ההיפך ממה שהגוף צריך אחרי גיל 30."',
    category: 'sports',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/05/tonal.webp',
    impactScore: 8.6,
    scientificConfidence: 9,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-17T14:00:00Z',
    lastUpdated: '2026-06-17T14:00:00Z',
    physiologicalImpact: ['מערכת השריר-שלד', 'sarcopenia', 'קורטיזול ומתח'],
    timeline: [{ id: 'ww-musc1', title: 'מאמר sarcopenia', description: 'למה אימוני כוח הכרחיים אחרי גיל 30.', timestamp: '2026-06-17T14:00:00Z' }]
  },
  {
    id: 'ww-lyma-gut-longevity',
    title: 'LYMA הופכת בריאות מעיים לפרוטוקול אריכות ימים: ריסט של 30 יום בהשראת Blue Zones',
    summary: 'פורמולת מעיים ארבע-ממדית שמבוססת על מה שהאוכלוסיות הארוכות-חיים בעולם באמת אוכלות.',
    content: 'LYMA, מותג תוספי מזון פרימיום, השיקה Gut Reset — פרוטוקול 30 ימים שמבוסס על מחקרי Blue Zones (אזורים בעולם עם ריכוז גבוה של אנשים שחיים מעל 100). הפורמולה כוללת 4 ממדים: פרוביוטיקה ממוקדת, סיבים תזונתיים מגוונים, פוליפנולים מזן ספציפי של זית, ו-butyrate (חומצה שומנית קצרת שרשרת).\n\n"הלקח מ-Blue Zones הוא לא רק מה לאכול, אלא איך לתמוך בחיידקים הנכונים במעי," אמר המדען הראשי של LYMA.',
    category: 'nutrition',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/ID2LifeStyle2-2-scaled.jpeg',
    impactScore: 8.2,
    scientificConfidence: 7.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-17T14:00:00Z',
    lastUpdated: '2026-06-17T14:00:00Z',
    physiologicalImpact: ['מיקרוביום המעי', 'אריכות ימים', 'Blue Zones'],
    timeline: [{ id: 'ww-lyma1', title: 'השקת LYMA Gut Reset', description: 'פרוטוקול מעיים בהשראת Blue Zones.', timestamp: '2026-06-17T14:00:00Z' }]
  },
  {
    id: 'ww-apple-perimenopause',
    title: 'Apple מוסיפה מעקב פרימנופאוזה לאפליקציית הבריאות — צעד ענק לבריאות נשים',
    summary: 'הפיצ\'ר החדש משתמש בהיסטוריית המחזור שלך כדי לזהות שינויים הורמונליים של פרימנופאוזה — לפני שרופא מאבחן.',
    content: 'Apple הכריזה על פיצ\'ר חדש באפליקציית Health שמנתח את היסטוריית המחזור החודשי ומזהה דפוסים שמעידים על תחילת פרימנופאוזה — תקופה שיכולה להתחיל כבר בגיל 40.\n\nהמערכת מזהה: שינויים באורך המחזור, שינויים בדימום, עלייה בתדירות גלי חום (מנתוני Apple Watch), וירידה באיכות שינה. "נשים מדווחות שהרגישו \'משהו לא בסדר\' שנים לפני אבחנה רשמית," אמרה סמנכ"לית הבריאות של Apple. "עכשיו יש כלי שמתרגם את ה-\'משהו\' הזה לנתונים."',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/apple-perimenopause.webp',
    impactScore: 9.0,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-15T14:00:00Z',
    lastUpdated: '2026-06-15T14:00:00Z',
    physiologicalImpact: ['בריאות נשים', 'הורמונים', 'פרימנופאוזה'],
    timeline: [{ id: 'ww-apple1', title: 'הכרזת Apple על מעקב פרימנופאוזה', description: 'פיצ\'ר חדש בריאות נשים.', timestamp: '2026-06-15T14:00:00Z' }]
  },
  {
    id: 'ww-therabody-cryotherm',
    title: 'Therabody CryoTherm Palm: כלי שמקרר את כפות הידיים בין סטים כדי להאט עייפות',
    summary: 'מכשיר כף יד שמשלב קירור וחימום — מיועד לקירור כפות ידיים בין סטים, ספרינטים ותרגילים להשהיית עייפות.',
    content: 'Therabody השיקה את CryoTherm Palm — מכשיר שמבוסס על מחקרים מסטנפורד שהדגימו כי קירור כפות הידיים בין סטים מעכב את עליית טמפרטורת הליבה של הגוף ומאפשר לבצע יותר חזרות ולהתאמן זמן ארוך יותר.\n\nהמכשיר מקרר ל-10°C תוך 30 שניות, ומחמם ל-42°C לשיקום אחרי אימון. "זה אחד הטריקים הכי פשוטים והכי יעילים בספורט," אמר ד"ר קרייג הלר מסטנפורד, שהמחקר שלו עומד מאחורי הטכנולוגיה.',
    category: 'sports',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/therabody-palm-cooling.jpg',
    impactScore: 8.4,
    scientificConfidence: 9,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-11T14:00:00Z',
    lastUpdated: '2026-06-11T14:00:00Z',
    physiologicalImpact: ['ויסות טמפרטורת גוף', 'ביצועי שרירים', 'שיקום'],
    timeline: [{ id: 'ww-thera1', title: 'השקת CryoTherm Palm', description: 'קירור כפות ידיים לשיפור ביצועים.', timestamp: '2026-06-11T14:00:00Z' }]
  },
  {
    id: 'ww-cold-plunge-truth',
    title: 'האמת הלא-סקסית על אמבטי קרח: למה רוב האנשים מפסיקים',
    summary: 'מה שצריך לדעת (ולהימנע ממנו) לפני שקונים cold plunge. הסיבות האמיתיות שרוב האנשים מוותרים.',
    content: 'Wellworthy פרסמה מאמר חשוב שחושף את הצד השני של טרנד ה-Cold Plunge: רוב האנשים מפסיקים להשתמש תוך 3-6 חודשים. הסיבות: תחזוקה יומית (סינון, ניקוי), עלות חשמל ($30-80/חודש), רעש ממערכת הקירור, וציפיות לא מציאותיות.\n\n"אנשים קונים אמבט ב-$5,000 כי ראו משפיען שעושה את זה. אחרי שבועיים, הם מגלים שצריך לנקות את המים כל 3 ימים ולהוסיף כלור." המאמר ממליץ: קודם נסו שבועיים של מקלחות קרות. אם שרדתם — אז שקלו השקעה.',
    category: 'body',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/05/coldtub.webp',
    impactScore: 7.8,
    scientificConfidence: 8,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "5 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-04T14:00:00Z',
    lastUpdated: '2026-06-04T14:00:00Z',
    physiologicalImpact: ['חשיפה לקור', 'בריאות מונעת', 'הרגלים'],
    timeline: [{ id: 'ww-cold2', title: 'מאמר האמת על Cold Plunge', description: 'למה רוב האנשים מוותרים.', timestamp: '2026-06-04T14:00:00Z' }]
  },
  {
    id: 'ww-oura-ring-5',
    title: 'Oura Ring 5 רשמית: הטבעת החכמה הקטנה בעולם — קטנה ב-40% עם ניטור בריאות לילי',
    summary: 'הדור החמישי קטן ב-40% מהקודם ומוסיף ניטור בריאות לילי שמזהה בעיות לפני שהן מתפתחות.',
    content: 'Oura חשפה את Ring 5 — הטבעת החכמה הקטנה ביותר שקיימת, קטנה ב-40% מ-Ring 4. הטבעת מוסיפה ניטור בריאות לילי שמזהה שינויים בדופק, טמפרטורה ו-HRV שיכולים להצביע על תחילת מחלה, עייפות כרונית או הפרעת שינה.\n\nהחיישן החדש גם מודד רוויית חמצן (SpO2) בצורה רציפה לאורך כל הלילה — לא רק דגימות כמו דגמים קודמים. סוללה: 7 ימים. מחיר: $349.',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/oura-5-scaled.jpg',
    impactScore: 9.1,
    scientificConfidence: 8.5,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "4 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-03T14:00:00Z',
    lastUpdated: '2026-06-03T14:00:00Z',
    physiologicalImpact: ['מעקב שינה', 'HRV ודופק', 'SpO2 רציף'],
    timeline: [{ id: 'ww-oura5', title: 'חשיפת Oura Ring 5', description: 'הטבעת הקטנה ביותר בעולם.', timestamp: '2026-06-03T14:00:00Z' }]
  },
  {
    id: 'ww-luna-voice-wearable',
    title: 'Luna: צמיד בריאות ללא מסך שמאפשר לתעד הרגלים בקול',
    summary: 'הטראקר המונע-קול משתמש במנוע אינטליגנציה שמספר לך בדיוק מתי להתאמן, לאכול ולנוח.',
    content: 'Luna היא צמיד בריאות ללא מסך עם גישה שונה לחלוטין: במקום להקליד או ללחוץ כפתורים, אתה פשוט מדבר. "שתיתי 2 כוסות מים" — והצמיד מתעד. "אכלתי סלט עם טונה" — נרשם.\n\nמנוע ה-AI של Luna מנתח את כל הנתונים (שינה, פעילות, תזונה) ומספק המלצות בזמן אמת דרך רמקול זעיר: "אתה ב-70% אנרגיה, מומלץ אימון Zone 2 של 30 דקות" או "הגוף שלך עייף, תעדיף הליכה היום."',
    category: 'health',
    imageUrl: 'https://wellworthy.com/wp-content/uploads/2026/06/lunaband.jpg',
    impactScore: 8.0,
    scientificConfidence: 7,
    clinicalStage: 'אישור FDA / זמין בשוק',
    readTime: "3 דק' קריאה",
    author: 'Wellworthy',
    source: 'Wellworthy',
    publishedAt: '2026-06-01T14:00:00Z',
    lastUpdated: '2026-06-01T14:00:00Z',
    physiologicalImpact: ['מעקב הרגלים', 'AI ובריאות', 'תזונה'],
    timeline: [{ id: 'ww-luna1', title: 'השקת Luna', description: 'צמיד בריאות קולי ללא מסך.', timestamp: '2026-06-01T14:00:00Z' }]
  }
];

export const MOCK_DEVELOPMENTS = [
  {
    articleId: 'featured-oura-ring-4',
    title: 'Oura Ring 4 קיבלה אישור CE לשוק האירופי',
    description: 'הטבעת מאושרת כעת למכירה גם באירופה. הצפי: 500,000 יחידות בשנה הראשונה.',
    physiologicalImpactAddition: ['אישורים רגולטוריים (CE/FDA)']
  },
  {
    articleId: 'whoop-glucose-integration',
    title: 'WHOOP 5.0 מקבלת שותפות עם Levels Health',
    description: 'שיתוף פעולה חדש עם Levels יאפשר תובנות גלוקוז מעמיקות ישירות באפליקציית WHOOP.',
    physiologicalImpactAddition: ['אינטגרציית נתוני גלוקוז']
  },
  {
    articleId: 'creatine-brain-study',
    title: 'מחקר המשך: קריאטין משפר ביצועים גם בגיל 70+',
    description: 'מחקר חדש מציג ששיפור קוגניטיבי מקריאטין חזק אפילו יותר בקרב מבוגרים.',
    physiologicalImpactAddition: ['תפקוד קוגניטיבי בגיל המבוגר']
  }
];
